apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: front-end-certificate
  namespace: {{ namespace }}
spec:
  secretName: front-end-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - {{ hostname }}
