apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: front-end
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: front-end
        branch: {{ git_branch }}
    spec:
      containers:
        - name: front-end-container
          image: ghcr.io/ruchira088/wordle-solver-front-end:{{ git_branch }}-{{ git_commit }}
          ports:
            - name: http-port
              containerPort: 80
          readinessProbe:
            httpGet:
              port: http-port
              path: /
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-readiness-probe
          livenessProbe:
            httpGet:
              port: http-port
              path: /
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-liveness-probe
          startupProbe:
            periodSeconds: 5
            failureThreshold: 5
            httpGet:
              port: http-port
              path: /
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-startup-probe
      imagePullSecrets:
        - name: docker-registry-credentials