apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: {{ namespace }}
spec:
  selector:
    app: front-end
    branch: {{ git_branch }}
  ports:
    - name: http-port
      port: 80
