- name: Fetch git information
  import_tasks: tasks/git-info.yml

- name: Remove existing production bundle
  file:
    path: ../build
    state: absent

- name: Set environment values in .env.production
  copy:
    content: |
      REACT_APP_GIT_BRANCH={{ git_branch }}
      REACT_APP_GIT_COMMIT={{ git_commit }}
      REACT_APP_BUILD_TIMESTAMP={{ ansible_date_time.iso8601 }}
    dest: ../.env.production

- name: Build production bundle
  shell: |
    cd ../ && \
      yarn install --frozen-lockfile && \
      yarn build

- name: Build Docker image
  shell: |
    docker build \
      -f docker/Dockerfile \
      -t wordle-solver-front-end:latest \
      -t wordle-solver-front-end:{{ git_branch }}-{{ git_commit }} \
      -t wordle-solver-front-end:{{ git_branch }}-{{ ansible_date_time.iso8601_basic_short }} \
      ../

- name: Clean up
  block:
    - name: Clean up production bundle
      file:
        path: ../build
        state: absent

    - name: Clean up production env file
      file:
        path: ../.env.production
        state: absent
