- name: Fetch git information
  import_tasks: tasks/git-info.yml

- name: Remove existing production bundle
  file:
    path: ../build
    state: absent

- name: Set environment values in .env.production
  copy:
    content: |
      REACT_APP_GIT_BRANCH={{ git_branch }}
      REACT_APP_GIT_COMMIT={{ git_commit }}
      REACT_APP_BUILD_TIMESTAMP={{ ansible_date_time.iso8601 }}
    dest: ../.env.production

- name: Build production bundle
  shell: |
    cd ../ && \
      yarn install --frozen-lockfile && \
      yarn build

- name: Build Docker image
  when: not publish
  shell: |
    docker build \
      -f docker/Dockerfile \
      -t ghcr.io/ruchira088/wordle-solver-front-end:{{ git_branch }} \
      -t ghcr.io/ruchira088/wordle-solver-front-end:{{ git_branch }}-{{ git_commit }} \
      ../

- name: Build and publish Docker image
  when: publish
  block:
    - name: Login to GitHub container registry
      command: docker login ghcr.io -u USERNAME -p {{ access_token }}
      vars:
        access_token: "{{ lookup('aws_ssm', '/github/packages/read-write-token', region='ap-southeast-2') }}"

    - name: Publish Docker image
      shell: |
        docker buildx build \
          --push \
          --platform linux/arm64,linux/amd64 \
          -t ghcr.io/ruchira088/wordle-solver-front-end:{{ git_branch }} \
          -t ghcr.io/ruchira088/wordle-solver-front-end:{{ git_branch }}-{{ git_commit }} \
          -f docker/Dockerfile \
          ../

- name: Clean up
  block:
    - name: Clean up production bundle
      file:
        path: ../build
        state: absent

    - name: Clean up production env file
      file:
        path: ../.env.production
        state: absent
