- name: Fetch git information
  import_tasks: tasks/git-info.yml

- name: Create K8s config
  copy:
    dest: k8s-output/kubeconfig
    content: "{{ lookup('aws_ssm', '/infrastructure/prod/k8s/config', region='ap-southeast-2') }}"

- set_fact:
    kube_config: k8s-output/kubeconfig
