version: 2.1

alias:
  - &install-ansible
    name: Install Ansible
    command: |
      sudo apt update && \
      sudo apt install software-properties-common ansible python3-pip -y && \
      pip3 install boto3 botocore openshift

  - &install-kubectl
    name: Install kubectl
    command: |
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && \
      echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list && \
      sudo apt update && \
      sudo apt install kubectl -y

jobs:
  build-and-publish-docker-image:
    docker:
      - image: cimg/node:lts
    steps:
      - setup_remote_docker
      - run: *install-ansible
      - checkout
      - run:
          name: Build and publish Docker image to Docker Hub
          command: ansible-playbook playbooks/build-and-publish-docker-image.yml

  deploy-to-k8s:
    docker:
      - image: cimg/base:stable
    steps:
      - run: *install-ansible
      - run: *install-kubectl
      - checkout
      - run:
          name: Deploy applications to K8s
          command: ansible-playbook playbooks/k8s-deploy.yml

orbs:
  slack: circleci/slack@3

workflows:
  version: 2

  video-downloader-front-end:
    jobs:
      - build-and-publish-docker-image:
          context:
            - aws-credentials
            - slack-webhook
          post-steps:
            - slack/status

      - deploy-to-k8s:
          context:
            - aws-credentials
            - slack-webhook
          requires:
            - build-and-publish-docker-image
          post-steps:
            - slack/status
