---
- hosts: localhost
  connection: local

  tasks:
    - name: Fetch git information
      import_tasks: tasks/git-info.yml

    - name: Build production Docker image
      import_tasks: tasks/build-docker.yml

    - name: Login to Docker Hub
      command: docker login -u {{ docker_username }} -p {{ docker_password }}
      vars:
        docker_username: "{{ lookup('aws_ssm', '/docker-hub/credentials/username', region='ap-southeast-2') }}"
        docker_password: "{{ lookup('aws_ssm', '/docker-hub/credentials/password', region='ap-southeast-2') }}"

    - name: Push Docker image
      shell: |
        docker tag wordle-solver-front-end:{{ git_branch }}-{{ git_commit }} ruchira088/wordle-solver-front-end:{{ git_branch }}-{{ git_commit }} && \
        docker push ruchira088/wordle-solver-front-end:{{ git_branch}}-{{ git_commit }}
