---
- hosts: localhost
  connection: local

  tasks:
    - name: Fetch git information
      import_tasks: tasks/git-info.yml

    - set_fact:
        namespace: "{{ 'wordle-solver-front-end' if env == 'production' else 'wordle-solver-front-end-' + git_branch }}"

    - name: Create K8s resource files
      import_tasks: tasks/k8s-resource-files.yml
      vars:
        hostname: "{{ 'wordle-solver.dev.ruchij.com' if env == 'production' else git_branch + '.wordle-solver.dev.ruchij.com' }}"

    - name: Create kubeconfig
      import_tasks: tasks/k8s-config.yml

    - name: Deploy to K8s
      block:
        - name: Create Namespace
          command: kubectl apply -f k8s-output/Namespace.yaml --kubeconfig {{ kube_config }}

        - name: Deploy application
          command: kubectl apply -f k8s-output --kubeconfig {{ kube_config }}

        - name: Wait for successful deployment
          command: kubectl rollout status deployment front-end-deployment --kubeconfig {{ kube_config }} -n {{ namespace }}

    - name: Delete output directory
      file:
        path: k8s-output
        state: absent
